language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install codecov -g
  - npm run test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: devfbrp.surge.sh
  project: ./build/
on:
  branch: master
  branch: develop
after_success:
  - codecov